services:
  identidade-acesso:
    build: .
    container_name: ct-identidade-acesso
    ports:
      - "${APP_PORT}:8080"
      - "5005:5005"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      - db
      - mongo
    networks:
      - microsservicos-dev

  db:
    image: postgres:15
    container_name: ct-postgres-identidade
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata-identidade:/var/lib/postgresql/data
    networks:
      - microsservicos-dev

  mongo:
    image: mongo:6
    container_name: ct-mongo-identidade
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodata-identidade:/data/db
    networks:
      - microsservicos-dev

volumes:
  pgdata-identidade:
  mongodata-identidade:

networks:
  microsservicos-dev:
    external: true