name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Fazer checkout do código
      - name: Checkout do código com submódulos
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2️⃣ Configurar Java 17
      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Build de cada microsserviço
      - name: Build identidade-acesso
        run: mvn clean package -DskipTests
        working-directory: microsservicos/identidade-acesso

      # 4️⃣ Definir versão dinâmica (build number)
      - name: Definir versão dinâmica
        run: echo "VERSION=0.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      # 5️⃣ Login no Docker Hub
      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 6️⃣ Build e push de todas as imagens
      - name: Build e push Docker
        run: |
          # identidade-acesso
          docker build -t ${{ secrets.DOCKER_USERNAME }}/identidade-acesso:${{ env.VERSION }} -t ${{ secrets.DOCKER_USERNAME }}/identidade-acesso:latest microsservicos/identidade-acesso
          docker push ${{ secrets.DOCKER_USERNAME }}/identidade-acesso:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/identidade-acesso:latest

          # material-estoque
          docker build -t ${{ secrets.DOCKER_USERNAME }}/material-estoque:latest microsservicos/material-estoque
          docker push ${{ secrets.DOCKER_USERNAME }}/material-estoque:latest

          # conteudo
          docker build -t ${{ secrets.DOCKER_USERNAME }}/conteudo:latest microsservicos/conteudo
          docker push ${{ secrets.DOCKER_USERNAME }}/conteudo:latest

          # ativos
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ativos:latest microsservicos/ativos
          docker push ${{ secrets.DOCKER_USERNAME }}/ativos:latest

          # ordem-manutencao
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ordem-manutencao:latest microsservicos/ordem-manutencao
          docker push ${{ secrets.DOCKER_USERNAME }}/ordem-manutencao:latest

      - name: Deploy na VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            whoami
            cd /home/mariabelarek/sistema-gestao-manutencao-industrial/microsservicos
            docker compose pull
            docker compose up -d